### ISSUE TITLE
linux编译不过

### ISSUE THREAD

**Issue by sourcema** [fengsheng666/FsdkObjSys#2]
为什么我在linux下编译不通过有问题，报这个问题：特例化成员‘FsdkObj::ImplClass<ObjTest>::_implSpaceName’需要‘template<>’语法
  std::string FsdkObj::ImplClass<classname>::_implSpaceName = #spacename;

**Comment by fengsheng666** [comment]
老兄 微信多少

**Comment by fengsheng666** [comment]
> 为什么我在linux下编译不通过有问题，报这个问题：特例化成员‘FsdkObj::ImplClass::_implSpaceName’需要‘template<>’语法 std::string FsdkObj::ImplClass::_implSpaceName = #spacename;

老兄微信多少

**Comment by sourcema** [comment]
> > 为什么我在linux下编译不通过有问题，报这个问题：特例化成员‘FsdkObj::ImplClass::_implSpaceName’需要‘template<>’语法 std::string FsdkObj::ImplClass::_implSpaceName = #spacename;
> 
> 老兄微信多少

我都忘了当初是要干嘛了，直接关闭吧。。。
